"""
causaliT Optuna Worker — SLURM Array Task

Called by each SLURM array job to execute one Optuna trial.
Loads the config fresh from disk, picks up an available trial via Optuna's
ask/tell API, trains, and reports the result.

Usage (invoked automatically by the SLURM script generated by optuna_parallel.py):

    python -m causaliT.euler_optuna.euler_optuna.optuna_worker \\
        --exp_dir /path/to/exp \\
        --home_exp_dir /home/path/to/exp \\
        --study_name capacity_study \\
        --data_dir /path/to/data \\
        --optimization_metric val_x_mae_mean \\
        --optimization_direction minimize \\
        --task_id $SLURM_ARRAY_TASK_ID \\
        --cluster
"""

import os
import re
import sys
import click
from pathlib import Path
from os.path import join
from functools import partial

import optuna
import torch
from omegaconf import OmegaConf

# ── causaliT imports ──────────────────────────────────────────────────────────
from causaliT.euler_optuna.euler_optuna.optuna_opt import objective_extended
from causaliT.euler_optuna.euler_optuna.cli import (
    sample_params_for_optuna,
    train_function_for_optuna,
    get_metrics_for_optuna,
)


# =============================================================================
# Trial-limit helper (mirrors optuna_parallel._get_trial_limit)
# =============================================================================

def _get_trial_limit(study, home_exp_dir: str):
    """
    Return the configured trial limit, or None if it cannot be determined.

    Precedence: study metadata → optuna*.yaml → None.
    """
    try:
        n = study.user_attrs.get("n_trials_total")
        if n is not None:
            return n
    except Exception:
        pass

    try:
        optuna_files = [f for f in os.listdir(home_exp_dir) if re.match(r"optuna.*\.yaml", f)]
        if len(optuna_files) == 1:
            cfg = OmegaConf.load(join(home_exp_dir, optuna_files[0]))
            n = cfg.get("n_trials", None)
            if n is not None:
                return n
    except Exception:
        pass

    return None


# =============================================================================
# Worker entry point
# =============================================================================

@click.command()
@click.option("--exp_dir",      required=True, help="Experiment directory (SCRATCH path if cluster)")
@click.option("--home_exp_dir", required=True, help="Home experiment directory (holds config files)")
@click.option("--study_name",   required=True, help="Optuna study name")
@click.option("--data_dir",     required=True, help="Root data directory")
@click.option("--optimization_metric",    default="val_x_mae_mean", help="Metric to optimise")
@click.option("--optimization_direction", default="minimize",        help="minimize or maximize")
@click.option("--task_id",      required=True, type=int, help="SLURM_ARRAY_TASK_ID")
@click.option("--cluster",      is_flag=True,  default=False, help="Running on cluster")
def main(
    exp_dir,
    home_exp_dir,
    study_name,
    data_dir,
    optimization_metric,
    optimization_direction,
    task_id,
    cluster,
):
    """Run one Optuna trial (called by SLURM array job)."""
    print(f"[Worker {task_id}] Starting")
    print(f"[Worker {task_id}] exp_dir      : {exp_dir}")
    print(f"[Worker {task_id}] home_exp_dir : {home_exp_dir}")

    # ── Load config fresh from home directory ─────────────────────────────────
    config_files = [
        f for f in os.listdir(home_exp_dir) if re.match(r"config.*\.yaml", f)
    ]
    if len(config_files) != 1:
        raise ValueError(
            f"Expected 1 config*.yaml in {home_exp_dir}, "
            f"found {len(config_files)}: {config_files}"
        )
    base_config = OmegaConf.load(join(home_exp_dir, config_files[0]))
    print(f"[Worker {task_id}] Loaded config: {config_files[0]}")

    # ── Load study ────────────────────────────────────────────────────────────
    storage = f"sqlite:///{join(exp_dir, 'optuna', 'study.db')}?timeout=60"
    study = optuna.load_study(study_name=study_name, storage=storage)
    print(f"[Worker {task_id}] Loaded study ({len(study.trials)} trials completed)")

    # ── Guard: check trial limit ──────────────────────────────────────────────
    n_trials_total = _get_trial_limit(study, home_exp_dir)
    if n_trials_total is not None:
        current = len(study.trials)
        if current >= n_trials_total:
            print(
                f"[Worker {task_id}] Limit reached ({current}/{n_trials_total}). "
                f"Exiting gracefully."
            )
            return
        print(f"[Worker {task_id}] Progress: {current}/{n_trials_total} trials")
    else:
        print(f"[Worker {task_id}] Warning: could not determine trial limit.")

    # ── Build objective ───────────────────────────────────────────────────────
    objective = partial(
        objective_extended,
        sample_params=lambda t: sample_params_for_optuna(t, base_config),
        train_function=train_function_for_optuna,
        get_metrics=get_metrics_for_optuna,
        config=base_config,
        exp_path=Path(exp_dir),
        data_dir=Path(data_dir),
        experiment_tag=f"optuna_{study_name}",
        cluster=cluster,
        optimization_metric=optimization_metric,
        optimization_direction=optimization_direction,
    )

    # ── CUDA ──────────────────────────────────────────────────────────────────
    if cluster and torch.cuda.is_available():
        torch.cuda.set_device(0)
        print(f"[Worker {task_id}] CUDA device: {torch.cuda.current_device()}")

    # ── Ask / tell ────────────────────────────────────────────────────────────
    trial = study.ask()
    print(f"[Worker {task_id}] Running trial {trial.number}")

    try:
        value = objective(trial)
        study.tell(trial, value)
        print(f"[Worker {task_id}] Trial {trial.number} done: {optimization_metric}={value:.6f}")
    except Exception as exc:
        import traceback
        print(f"[Worker {task_id}] ERROR in trial {trial.number}: {exc}")
        traceback.print_exc()
        study.tell(trial, state=optuna.trial.TrialState.FAIL)
        sys.exit(1)


if __name__ == "__main__":
    main()
