"""
Configuration utilities for CausaliT training.

This module provides functions for populating configuration values from dataset metadata.
"""

import json
from os.path import join, exists
from typing import Dict, Any

from omegaconf import OmegaConf, DictConfig


class DatasetMetadataError(Exception):
    """Raised when dataset_metadata.json is missing or invalid."""
    pass


def load_dataset_metadata(data_dir: str, dataset: str) -> Dict[str, Any]:
    """
    Load dataset metadata from the dataset folder.
    
    The metadata file (dataset_metadata.json) is generated by SCMDataset.generate_ds()
    and contains all information needed for training and evaluation:
    - variable_info: n_source, n_input, n_target, source_labels, input_labels, target_labels
    - causal_structure: direct_edges, transitive_closure, expected_effects
    - variable_index_map: mapping from variable names to indices
    
    Args:
        data_dir: Path to the data directory (e.g., "data/")
        dataset: Dataset name (e.g., "scm1_linear_gaussian")
        
    Returns:
        Dict containing dataset metadata
        
    Raises:
        DatasetMetadataError: If dataset_metadata.json is not found or invalid
        
    Example:
        >>> metadata = load_dataset_metadata("data", "scm1_linear_gaussian")
        >>> print(metadata["variable_info"]["n_source"])  # 5
    """
    metadata_path = join(data_dir, dataset, "dataset_metadata.json")
    
    if not exists(metadata_path):
        raise DatasetMetadataError(
            f"Dataset metadata file not found: {metadata_path}\n\n"
            f"The dataset_metadata.json file is required for training.\n"
            f"For SCM datasets, this file is automatically generated by SCMDataset.generate_ds().\n"
            f"For real-world datasets, you need to create this file manually.\n\n"
            f"See docs/DATASET_METADATA.md for the required format and minimal template."
        )
    
    try:
        with open(metadata_path, 'r', encoding='utf-8') as f:
            metadata = json.load(f)
    except json.JSONDecodeError as e:
        raise DatasetMetadataError(
            f"Invalid JSON in dataset metadata file: {metadata_path}\n"
            f"Error: {e}"
        )
    
    # Validate required fields for training
    required_fields = ["variable_info"]
    for field in required_fields:
        if field not in metadata:
            raise DatasetMetadataError(
                f"Missing required field '{field}' in dataset metadata: {metadata_path}\n"
                f"See docs/DATASET_METADATA.md for the required format."
            )
    
    var_info = metadata.get("variable_info", {})
    required_var_fields = ["n_source", "n_input", "n_target"]
    for field in required_var_fields:
        if field not in var_info:
            raise DatasetMetadataError(
                f"Missing required field 'variable_info.{field}' in dataset metadata: {metadata_path}\n"
                f"See docs/DATASET_METADATA.md for the required format."
            )
    
    return metadata


def populate_seq_lengths_from_dataset(
    config: DictConfig,
    data_dir: str,
) -> DictConfig:
    """
    Populate sequence length and embedding configuration from dataset metadata.
    
    This function reads the dataset_metadata.json file and populates:
    
    **Sequence Lengths (used by attention masks, model architecture):**
    - config.data.S_seq_len = variable_info.n_source
    - config.data.X_seq_len = variable_info.n_input
    - config.data.Y_seq_len = variable_info.n_target
    
    **Embedding Dimensions (for nn.Embedding lookup tables):**
    
    For non-shared embeddings (each stage has its own embedding table):
    - config.data.num_embeddings_X = n_input + 1  (for X stage, +1 for padding_idx=0)
    - config.data.num_embeddings_Y = n_target + 1 (for Y stage, if Y exists)
    
    For shared embeddings (one lookup table for all variables):
    - config.data.num_embeddings_shared = n_source + n_input + n_target + 1
    
    Note: OrthogonalMaskEmbedding (S) uses num_variables directly (no +1 needed)
    because it handles var_id_offset internally.
    
    Args:
        config: OmegaConf configuration dictionary
        data_dir: Path to the data directory
        
    Returns:
        Modified config with populated sequence lengths and embedding dimensions
        
    Raises:
        DatasetMetadataError: If dataset_metadata.json is not found or invalid
        
    Example:
        >>> config = OmegaConf.load("config.yaml")
        >>> config = populate_seq_lengths_from_dataset(config, "data")
        >>> print(config.data.S_seq_len)  # Number of S variables
        >>> print(config.data.num_embeddings_X)  # For X nn.Embedding
    """
    dataset = config["data"]["dataset"]
    
    # Load metadata
    metadata = load_dataset_metadata(data_dir, dataset)
    var_info = metadata["variable_info"]
    
    # Populate sequence lengths
    # We need to make the config mutable if it isn't already
    if OmegaConf.is_readonly(config):
        OmegaConf.set_readonly(config, False)
    
    n_source = var_info["n_source"]
    n_input = var_info["n_input"]
    n_target = var_info["n_target"]
    
    # Sequence lengths (used for attention masks, model dimensions)
    config["data"]["S_seq_len"] = n_source
    config["data"]["X_seq_len"] = n_input
    config["data"]["Y_seq_len"] = n_target
    
    # Embedding dimensions for nn.Embedding lookup tables
    # +1 accounts for padding_idx=0 (variable indices are 1-indexed: X1=1, X2=2, ...)
    
    # Per-stage embeddings (non-shared): each stage has its own enumeration 1,2,3,...
    # +1 accounts for padding_idx=0 (variable indices are 1-indexed: S1=1, X1=1, ...)
    config["data"]["num_embeddings_S"] = n_source + 1
    config["data"]["num_embeddings_X"] = n_input + 1
    config["data"]["num_embeddings_Y"] = n_target + 1 if n_target > 0 else 0
    
    # Shared embedding (if using one lookup table for all S, X, Y variables)
    config["data"]["num_embeddings_shared"] = n_source + n_input + n_target + 1
    
    # Feature indices (which column in data tensor corresponds to which feature)
    # For SCM datasets: {value: 0, variable: 1}
    # For real-world datasets: may vary (e.g., dyconex has additional descriptive features)
    feature_indices = metadata.get("feature_indices", {"value": 0, "variable": 1})
    
    # Populate feature_indices directly at data level (flat structure)
    config["data"]["feature_indices"] = OmegaConf.create(feature_indices)
    
    print(f"Loaded dataset dimensions from metadata ({dataset}):")
    print(f"  S_seq_len: {n_source}")
    print(f"  X_seq_len: {n_input}")
    print(f"  Y_seq_len: {n_target}")
    print(f"  num_embeddings_S: {n_source + 1} (non-shared, includes padding)")
    print(f"  num_embeddings_X: {n_input + 1} (non-shared, includes padding)")
    print(f"  num_embeddings_Y: {n_target + 1 if n_target > 0 else 0}")
    print(f"  num_embeddings_shared: {n_source + n_input + n_target + 1} (for shared embedding)")
    print(f"  feature_indices: {feature_indices}")
    
    return config


def validate_dataset_metadata_for_evaluation(
    data_dir: str,
    dataset: str,
    required_features: list = None,
) -> Dict[str, Any]:
    """
    Validate that dataset metadata contains fields required for specific evaluations.
    
    Different evaluation functions require different metadata fields:
    - Training: variable_info.{n_source, n_input, n_target}
    - eval_embed: variable_info.{source_labels, input_labels}
    - eval_interventions: causal_structure.expected_effects
    - eval_attention_scores: causal_structure.direct_edges
    
    Args:
        data_dir: Path to the data directory
        dataset: Dataset name
        required_features: List of feature names to validate. Options:
            - "training": Basic training requirements
            - "labels": Variable labels (for embedding analysis)
            - "expected_effects": For intervention invariance tests
            - "edges": For DAG recovery evaluation
            
    Returns:
        Dict containing dataset metadata (if valid)
        
    Raises:
        DatasetMetadataError: If required fields are missing
    """
    metadata = load_dataset_metadata(data_dir, dataset)
    
    if required_features is None:
        required_features = ["training"]
    
    missing_fields = []
    
    for feature in required_features:
        if feature == "training":
            # Already validated in load_dataset_metadata
            pass
        
        elif feature == "labels":
            var_info = metadata.get("variable_info", {})
            for label_field in ["source_labels", "input_labels"]:
                if label_field not in var_info or not var_info[label_field]:
                    missing_fields.append(f"variable_info.{label_field}")
        
        elif feature == "expected_effects":
            causal = metadata.get("causal_structure", {})
            if "expected_effects" not in causal:
                missing_fields.append("causal_structure.expected_effects")
        
        elif feature == "edges":
            causal = metadata.get("causal_structure", {})
            if "direct_edges" not in causal:
                missing_fields.append("causal_structure.direct_edges")
    
    if missing_fields:
        raise DatasetMetadataError(
            f"Dataset metadata is missing required fields for {required_features}:\n"
            f"  Missing: {', '.join(missing_fields)}\n"
            f"  File: {join(data_dir, dataset, 'dataset_metadata.json')}\n"
            f"See docs/DATASET_METADATA.md for the required format."
        )
    
    return metadata
