experiment:
  name: test
  n_nodes: 4
  n_source: 1
  n_input: 3
data:
  dataset: random_n4_k2_linear_gaussian_s1000
  data_root: C:\Users\ScipioneFrancesco\Documents\Projects\causaliT\.pytest_tmp\test_group_config_is_staged_fo0\datasets
training:
  seed: 0
  learning_rate: 0.001
