"""Part 1: header markdown + setup code cell."""
import nbformat as nbf

md = (
    "# Query dynamics and structural recovery — plain (non-adaptive) run\n"
    "\n"
    "Simplified evaluation notebook for runs trained with the **plain trainer**\n"
    "(no `adaptive_training`): a single phase, checkpoints in `k_0/checkpoints/`,\n"
    "metrics in `k_0/logs/csv/version_0/metrics.csv`. All adaptive machinery\n"
    "(phase shading, transitions, dir_bias, dropout selection) and the\n"
    "nodewise/centroid-commit sections are removed.\n"
    "\n"
    "**Questions.** 1. **Hygiene** — R2 first; train/val curves; NOTEARS/L0.\n"
    "2. **Convergence** — `cos(q_i, c_i)` to the true-parent key centroid.\n"
    "3. **Gradient field** — offline eval-mode HSIC gradients per checkpoint.\n"
    "4. **Movement** — per-node query displacement and norm-budget steps\n"
    "(the epoch-0 interval, the lazy centroid write, is excluded).\n"
    "5. **Structural recovery** — edge posterior, SHD, Q-vs-M attribution.\n"
    "\n"
    "**Notes.** Node order `[S1, S2, X1..X18]`; `GT[i, j] = 1` means `j -> i`.\n"
    "`epoch0-initial.ckpt` is the raw init BEFORE the lazy centroid write.\n"
    "Derived state is cached under `eval_cache/`; delete it to force recompute."
)

setup = (
    "import hashlib\n"
    "import json\n"
    "import re\n"
    "import sys\n"
    "from pathlib import Path\n"
    "\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import torch\n"
    "import matplotlib.pyplot as plt\n"
    "import yaml\n"
    "from matplotlib.patches import Rectangle\n"
    "from omegaconf import OmegaConf\n"
    "\n"
    "# ---- Repo root and folders -------------------------------------------------\n"
    "ROOT = Path.cwd()\n"
    "while not (ROOT / \"causaliT\").is_dir() and ROOT != ROOT.parent:\n"
    "    ROOT = ROOT.parent\n"
    "\n"
    "EXP_DIR = Path.cwd()                        # notebook lives in the experiment folder\n"
    "if not (EXP_DIR / \"config.yaml\").exists():\n"
    "    raise FileNotFoundError(\"run the notebook from inside the experiment folder\")\n"
    "CKPT_DIR = EXP_DIR / \"k_0\" / \"checkpoints\"\n"
    "METRICS_CSV = EXP_DIR / \"k_0\" / \"logs\" / \"csv\" / \"version_0\" / \"metrics.csv\"\n"
    "HPARAMS = EXP_DIR / \"k_0\" / \"logs\" / \"csv\" / \"version_0\" / \"hparams.yaml\"\n"
    "FIG_DIR = EXP_DIR / \"fig_eval\"\n"
    "FIG_DIR.mkdir(parents=True, exist_ok=True)\n"
    "\n"
    "# ---- Dataset folder (config data_root, with local fallbacks) ----------------\n"
    "cfg = OmegaConf.load(EXP_DIR / \"config.yaml\")\n"
    "cand = [Path(str(cfg.data.data_root)) / str(cfg.data.dataset),\n"
    "        ROOT / \"data\" / str(cfg.data.dataset),\n"
    "        ROOT / \"experiments/6_INVESTIGATIONS/LARGER_DAGS/baseline\" / str(cfg.data.dataset)]\n"
    "DATA_DIR = next(p for p in cand if (p / \"dec1_cross_att_mask.csv\").exists())\n"
    "\n"
    "# ---- Gate constants (resolved values from hparams.yaml) ---------------------\n"
    "hp = yaml.safe_load(open(HPARAMS))\n"
    "mk = hp[\"model\"][\"kwargs\"]\n"
    "F_FANIN = float(mk[\"query_fanin_scale\"])   # query_fanin_scale (auto -> N*x(p*)^2)\n"
    "BETA = float(mk[\"init_tau_self\"])          # existence-gate temperature\n"
    "GAMMA = float(mk[\"init_gamma\"])            # Hard-Concrete stretch lower bound\n"
    "ZETA = float(mk[\"init_zeta\"])              # Hard-Concrete stretch upper bound\n"
    "DIR_BETA = float(mk[\"dir_tau_self\"])       # direction-gate temperature\n"
    "L0_OFFSET = BETA * np.log(-GAMMA / ZETA)  # = 0: the gate opens at logit 0\n"
    "\n"
    "N_S = int(cfg.experiment.n_source)\n"
    "N_X = int(cfg.experiment.n_input)\n"
    "NODES = [f\"S{i}\" for i in range(1, N_S + 1)] + [f\"X{i}\" for i in range(1, N_X + 1)]\n"
    "N = len(NODES)\n"
    "\n"
    "# ---- Plot style -------------------------------------------------------------\n"
    "EXPORT_FORMATS = []           # e.g. [\"png\", \"pdf\", \"svg\"] to export figures\n"
    "plt.rcParams.update({\n"
    "    \"font.size\": 12, \"axes.titlesize\": 14, \"axes.labelsize\": 12,\n"
    "    \"xtick.labelsize\": 12, \"ytick.labelsize\": 12, \"axes.titleweight\": \"bold\",\n"
    "})\n"
    "OKABE_ITO = [\"#0072B2\", \"#E69F00\", \"#009E73\", \"#D55E00\", \"#CC79A7\",\n"
    "             \"#56B4E9\", \"#F0E442\", \"#000000\"]\n"
    "\n"
    "metrics = pd.read_csv(METRICS_CSV)\n"
    "E_MAX = metrics[\"epoch\"].max()\n"
    "\n"
    "\n"
    "def save_fig(fig, name):\n"
    "    for fmt in EXPORT_FORMATS:\n"
    "        fig.savefig(FIG_DIR / f\"{name}.{fmt}\", bbox_inches=\"tight\")\n"
    "\n"
    "\n"
    "def mark_gt(ax):\n"
    "    # Vermillion frame on every true-edge cell (GT[i, j] = 1 <=> j -> i).\n"
    "    for i, j in zip(*np.where(GT == 1)):\n"
    "        ax.add_patch(Rectangle((j - 0.5, i - 0.5), 1, 1, fill=False,\n"
    "                               edgecolor=\"#D55E00\", lw=1.2))\n"
    "\n"
    "\n"
    "def metric_series(col):\n"
    "    s = metrics[[\"epoch\", col]].dropna()\n"
    "    return s[\"epoch\"].values, s[col].values\n"
    "\n"
    "\n"
    "def last_value(col):\n"
    "    # Last non-NaN value of a metrics column (plain run: no summary JSON).\n"
    "    if col not in metrics:\n"
    "        return None\n"
    "    s = metrics[col].dropna()\n"
    "    return float(s.iloc[-1]) if len(s) else None\n"
    "\n"
    "\n"
    "print(f\"EXP_DIR={EXP_DIR.name} | DATA_DIR={DATA_DIR} | F_FANIN={F_FANIN:.4f} | \"\n"
    "      f\"epochs 0..{E_MAX}\")"
)

nb = nbf.v4.new_notebook(cells=[nbf.v4.new_markdown_cell(md), nbf.v4.new_code_cell(setup)])
nbf.write(nb, "scripts/_nb_part1.ipynb")
print("part1 ok")
