"""Part 3: ground truth + per-checkpoint (Q, K, M) state (cached)."""
import nbformat as nbf

md = (
    "## 2. Ground truth and per-checkpoint query/key state\n"
    "\n"
    "GT assembled in model node order from `dec1_cross_att_mask.csv` (S->X) and\n"
    "`dec1_self_att_mask.csv` (X->X), convention `[child, parent] = 1`. With the\n"
    "frozen orthonormal key frame and free queries, the eval-mode structural state\n"
    "of each checkpoint is the triple `(Q, K, M)`."
)

c1 = (
    "# ---- Ground truth ----------------------------------------------------------------------------\n"
    "cross_gt = pd.read_csv(DATA_DIR / \"dec1_cross_att_mask.csv\", index_col=0)  # (N_X, N_S)\n"
    "self_gt = pd.read_csv(DATA_DIR / \"dec1_self_att_mask.csv\", index_col=0)    # (N_X, N_X)\n"
    "assert list(cross_gt.index) == NODES[N_S:] and list(cross_gt.columns) == NODES[:N_S]\n"
    "assert list(self_gt.index) == NODES[N_S:] and list(self_gt.columns) == NODES[N_S:]\n"
    "GT = np.zeros((N, N))\n"
    "GT[N_S:, :N_S] = cross_gt.values      # S -> X block\n"
    "GT[N_S:, N_S:] = self_gt.values       # X -> X block (S rows stay zero: sources)\n"
    "PA = GT.astype(bool)                  # [i, j]: j is a parent of i\n"
    "HAS_PAR = PA.any(axis=1)              # X nodes with >= 1 GT parent\n"
    "print(f\"GT edges: {int(GT.sum())} (S->X: {int(cross_gt.values.sum())}, \"\n"
    "      f\"X->X: {int(self_gt.values.sum())})\")"
)

c2 = (
    "# ---- (Q, K, M) per checkpoint (cached) ------------------------------------------\n"
    "def load_qkm(ckpt_path):\n"
    "    # (Q, K, M) from a checkpoint: queries, fixed frame, norm budget.\n"
    "    sd = torch.load(ckpt_path, map_location=\"cpu\", weights_only=False)[\"state_dict\"]\n"
    "    q = torch.cat([sd[\"model.query_embed_S.embedding.weight\"][1:],\n"
    "                   sd[\"model.query_embed_X.embedding.weight\"][1:]]).double().numpy()\n"
    "    k = torch.cat([sd[\"model.orth_embed_S.frame\"],\n"
    "                   sd[\"model.orth_embed_X.frame\"]]).double().numpy()\n"
    "    m = sd[\"model.attention.inner_attention.query_norm_log_scale\"].exp().double().numpy()\n"
    "    return q, k, m\n"
    "\n"
    "\n"
    "def ckpt_epoch(path):\n"
    "    if path.name.startswith(\"epoch0-initial\"):\n"
    "        return 0   # raw init, BEFORE the lazy centroid write (first train batch)\n"
    "    m = re.match(r\"epoch=(\\d+)-\", path.name)\n"
    "    return int(m.group(1)) if m else None\n"
    "\n"
    "\n"
    "ckpts = {e: p for p in CKPT_DIR.glob(\"*.ckpt\") if (e := ckpt_epoch(p)) is not None}\n"
    "EPOCHS = sorted(ckpts)\n"
    "BASE = 1 if len(EPOCHS) > 1 else 0   # first post-init ckpt: baseline for \"gain\"\n"
    "print(f\"{len(ckpts)} checkpoints, epochs {EPOCHS[0]}..{EPOCHS[-1]}\")\n"
    "\n"
    "# ---- Cache of derived checkpoint state ---------------------------------------------\n"
    "CACHE_FILE = EXP_DIR / \"eval_cache\" / \"derived_state.npz\"\n"
    "\n"
    "\n"
    "def cache_key():\n"
    "    # Checkpoints (name + mtime) + gate constants: any change invalidates.\n"
    "    parts = [f\"{e}:{ckpts[e].name}:{ckpts[e].stat().st_mtime_ns}\" for e in EPOCHS]\n"
    "    consts = f\"F={F_FANIN!r}|dirB={DIR_BETA!r}|L0={float(L0_OFFSET)!r}\"\n"
    "    return hashlib.sha256((consts + \"|\" + \"|\".join(parts)).encode()).hexdigest()\n"
    "\n"
    "\n"
    "CACHE_KEY = cache_key()\n"
    "\n"
    "\n"
    "def cache_load():\n"
    "    if CACHE_FILE.exists():\n"
    "        try:\n"
    "            c = np.load(CACHE_FILE, allow_pickle=False)\n"
    "            if str(c[\"cache_key\"]) == CACHE_KEY:\n"
    "                return {k: c[k] for k in c.files}\n"
    "        except Exception:\n"
    "            pass\n"
    "    return None\n"
    "\n"
    "\n"
    "def cache_save(**arrays):\n"
    "    CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)\n"
    "    np.savez(CACHE_FILE, cache_key=np.str_(CACHE_KEY), **arrays)\n"
    "    print(f\"cache written: {CACHE_FILE}\")\n"
    "\n"
    "\n"
    "CKP = cache_load() or {}\n"
    "if {\"Q\", \"K\", \"M\"} <= set(CKP):\n"
    "    Q, K, M = CKP[\"Q\"], CKP[\"K\"], CKP[\"M\"]\n"
    "    print(\"loaded cached (Q, K, M)\")\n"
    "else:\n"
    "    Q, K, M = [], None, []\n"
    "    for e in EPOCHS:\n"
    "        q, k, m = load_qkm(ckpts[e])\n"
    "        Q.append(q); M.append(m)\n"
    "        K = k if K is None else k\n"
    "        assert np.allclose(k, K), \"the key frame must be frozen\"\n"
    "    Q, M = np.stack(Q), np.stack(M)                    # (E, N, d), (E, N)\n"
    "    cache_save(Q=Q, K=K, M=M)\n"
    "gram = K @ K.T\n"
    "print(f\"key frame: max off-diagonal |gram| = \"\n"
    "      f\"{np.abs(gram - np.diag(np.diag(gram))).max():.2e} (orthonormal)\")\n"
    "\n"
    "QH = Q / np.linalg.norm(Q, axis=2, keepdims=True)        # unit queries (E, N, d)"
)

cells = [nbf.v4.new_markdown_cell(md)] + [nbf.v4.new_code_cell(c) for c in (c1, c2)]
nbf.write(nbf.v4.new_notebook(cells=cells), "scripts/_nb_part3.ipynb")
print("part3 ok")
