"""Part 4: centroid alignment heatmap + curves."""
import nbformat as nbf

md = (
    "## 3. Do the queries converge to their parents' centroid?\n"
    "\n"
    "With the frozen orthonormal key frame, the structurally optimal position of\n"
    "query *i* is the centroid of the keys of its true parents. The heatmap shows\n"
    "`cos(q_i, centroid(keys of true parents))` per checkpoint; NaN for parent-less\n"
    "source nodes."
)

c1 = (
    "# ---- True-parent key centroids and alignment --------------------------------------\n"
    "C = np.full((N, K.shape[1]), np.nan)\n"
    "for i in range(N):\n"
    "    pa = np.where(GT[i] == 1)[0]\n"
    "    if len(pa):\n"
    "        c = K[pa].mean(axis=0)\n"
    "        C[i] = c / np.linalg.norm(c)\n"
    "\n"
    "ALIGN = np.einsum(\"end,nd->en\", QH, C)                 # cos(q_i, c_i), (E, N)\n"
    "c_all = K.mean(axis=0)\n"
    "c_all = c_all / np.linalg.norm(c_all)\n"
    "ALIGN_INIT = QH @ c_all                                # drift from the init point\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(7.2, 4.6))\n"
    "im = ax.imshow(np.ma.masked_invalid(ALIGN.T), aspect=\"auto\", cmap=\"RdBu_r\",\n"
    "               vmin=-1, vmax=1,\n"
    "               extent=[EPOCHS[0], EPOCHS[-1], N - 0.5, -0.5])\n"
    "ax.set_yticks(range(N), NODES)\n"
    "ax.set_xlabel(\"epoch [-]\")\n"
    "ax.set_ylabel(\"child i\")\n"
    "ax.set_title(\"cos(query, true-parent centroid)\")\n"
    "fig.colorbar(im, ax=ax, label=\"cosine [-]\")\n"
    "fig.tight_layout()\n"
    "save_fig(fig, \"centroid_alignment_heatmap\")\n"
    "plt.show()\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(7.2, 3.8))\n"
    "xa = ALIGN[:, N_S:]\n"
    "ax.plot(EPOCHS, np.nanmean(xa, axis=1), color=OKABE_ITO[0], lw=1.4,\n"
    "        label=\"mean over X nodes\")\n"
    "ax.plot(EPOCHS, np.nanmin(xa, axis=1), color=OKABE_ITO[3], lw=1.2, ls=\"--\",\n"
    "        label=\"min over X nodes\")\n"
    "ax.plot(EPOCHS, ALIGN_INIT.mean(axis=1), color=OKABE_ITO[2], lw=1.2, ls=\":\",\n"
    "        label=\"mean cos(q, init centroid)\")\n"
    "ax.set_xlim(min(EPOCHS), max(EPOCHS))\n"
    "ax.set_xlabel(\"epoch [-]\")\n"
    "ax.set_ylabel(\"cosine [-]\")\n"
    "ax.set_title(\"Alignment with the optimum\")\n"
    "ax.legend(fontsize=9)\n"
    "fig.tight_layout()\n"
    "save_fig(fig, \"centroid_alignment_curves\")\n"
    "plt.show()\n"
    "\n"
    "for e in [EPOCHS[BASE], EPOCHS[len(EPOCHS) // 2], EPOCHS[-1]]:\n"
    "    i = EPOCHS.index(e)\n"
    "    print(f\"epoch {e:5d}: centroid alignment mean={np.nanmean(ALIGN[i, N_S:]):+.4f} \"\n"
    "          f\"min={np.nanmin(ALIGN[i, N_S:]):+.4f}\")"
)

cells = [nbf.v4.new_markdown_cell(md), nbf.v4.new_code_cell(c1)]
nbf.write(nbf.v4.new_notebook(cells=cells), "scripts/_nb_part4.ipynb")
print("part4 ok")
