"""Part 6: gradient-field views (heatmaps + summary curves)."""
import nbformat as nbf

c1 = (
    "# ---- Gradient field views (parent alignment / radial share / norm) ------------------\n"
    "GN = np.linalg.norm(G, axis=2)                        # (Eg, N)\n"
    "GH = G / np.maximum(GN[..., None], 1e-12)             # unit gradient rows\n"
    "G_PAR = np.einsum(\"end,nd->en\", -GH, C)               # cos(-g_i, c_i): + = toward parents\n"
    "QH_G = QH[GIDX]                                       # unit queries at the grad ckpts\n"
    "G_RAD = np.abs(np.einsum(\"end,end->en\", GH, QH_G))    # |cos(g_i, q_i)|\n"
    "\n"
    "fig, axes = plt.subplots(1, 3, figsize=(17.5, 4.6))\n"
    "\n"
    "im = axes[0].imshow(np.ma.masked_invalid(G_PAR.T), aspect=\"auto\", cmap=\"RdBu_r\",\n"
    "                    vmin=-1, vmax=1,\n"
    "                    extent=[G_EPOCHS[0], G_EPOCHS[-1], N - 0.5, -0.5])\n"
    "axes[0].set_yticks(range(N), NODES)\n"
    "axes[0].set_xlabel(\"epoch [-]\")\n"
    "axes[0].set_ylabel(\"node i\")\n"
    "axes[0].set_title(\"Gradient-parent alignment  cos(-g_i, c_i)\")\n"
    "fig.colorbar(im, ax=axes[0], label=\"cosine [-]\")\n"
    "\n"
    "im = axes[1].imshow(G_RAD.T, aspect=\"auto\", cmap=\"magma\", vmin=0, vmax=1,\n"
    "                    extent=[G_EPOCHS[0], G_EPOCHS[-1], N - 0.5, -0.5])\n"
    "axes[1].set_yticks(range(N), NODES)\n"
    "axes[1].set_xlabel(\"epoch [-]\")\n"
    "axes[1].set_title(\"Radial share  |cos(g_i, q_i)|  (1 = no directional info)\")\n"
    "fig.colorbar(im, ax=axes[1], label=\"|cos| [-]\")\n"
    "\n"
    "im = axes[2].imshow(np.log10(GN.T + 1e-12), aspect=\"auto\", cmap=\"viridis\",\n"
    "                    extent=[G_EPOCHS[0], G_EPOCHS[-1], N - 0.5, -0.5])\n"
    "axes[2].set_yticks(range(N), NODES)\n"
    "axes[2].set_xlabel(\"epoch [-]\")\n"
    "axes[2].set_title(\"Gradient norm  log10 ||g_i||\")\n"
    "fig.colorbar(im, ax=axes[2], label=\"log10 [-]\")\n"
    "\n"
    "fig.tight_layout()\n"
    "save_fig(fig, \"gradient_field_heatmaps\")\n"
    "plt.show()\n"
    "\n"
    "# ---- Summary curves ---------------------------------------------------------------------\n"
    "fig, ax = plt.subplots(figsize=(7.6, 3.8))\n"
    "gp = G_PAR[:, N_S:]\n"
    "ax.plot(G_EPOCHS, np.nanmean(gp, axis=1), color=OKABE_ITO[0], lw=1.4,\n"
    "        label=\"mean cos(-g, parent centroid), X\")\n"
    "ax.plot(G_EPOCHS, np.nanmin(gp, axis=1), color=OKABE_ITO[3], lw=1.1, ls=\"--\",\n"
    "        label=\"min, X\")\n"
    "ax.plot(G_EPOCHS, G_RAD.mean(axis=1), color=OKABE_ITO[2], lw=1.1, ls=\":\",\n"
    "        label=\"mean radial share\")\n"
    "ax.axhline(0, color=\"#999999\", lw=0.8)\n"
    "ax.set_xlim(G_EPOCHS[0], G_EPOCHS[-1])\n"
    "ax.set_xlabel(\"epoch [-]\")\n"
    "ax.set_ylabel(\"[-]\")\n"
    "ax.set_title(\"Gradient field over training\")\n"
    "ax.legend(fontsize=9)\n"
    "fig.tight_layout()\n"
    "save_fig(fig, \"gradient_field_curves\")\n"
    "plt.show()\n"
    "\n"
    "print(f\"gradient-parent alignment: mean over X, first ckpt \"\n"
    "      f\"{np.nanmean(gp[0]):+.3f} -> last {np.nanmean(gp[-1]):+.3f}; \"\n"
    "      f\"radial share mean {G_RAD[0].mean():.2f} -> {G_RAD[-1].mean():.2f}\")"
)

nbf.write(nbf.v4.new_notebook(cells=[nbf.v4.new_code_cell(c1)]),
          "scripts/_nb_part6.ipynb")
print("part6 ok")
