"""Part 8: structural recovery — edge posterior, SHD, Q-vs-M attribution."""
import nbformat as nbf

md = (
    "## 6. Structural recovery: edge posterior, SHD, and the Q-vs-M attribution\n"
    "\n"
    "From the `(Q, K, M)` state of each checkpoint, the deterministic eval-mode\n"
    "probe gives the directed edge posterior\n"
    "`pi[i, j] = sigmoid(S_sym - L0_offset) * sigmoid(A_anti / dir_beta)` with\n"
    "`raw = (q_hat_i * M_i) . k_j * sqrt(F_FANIN)` (same formula as\n"
    "`GatedSelfAttention.structure_posterior`; zero diagonal). SHD is the straight\n"
    "Hamming distance on directed cells.\n"
    "\n"
    "**Q-vs-M attribution.** The posterior is recomputed with one channel frozen\n"
    "at its post-init value; whichever single-channel curve reproduces the full\n"
    "SHD trajectory identifies the channel carrying the structural learning."
)

c1 = (
    "# ---- Directed edge posterior per checkpoint ------------------------------------------\n"
    "SQRT_F = np.sqrt(F_FANIN)\n"
    "DAG_THRESHOLD = 0.5\n"
    "\n"
    "def edge_posterior(q, k, m):\n"
    "    # pi[i, j] = P(j -> i), zero diagonal.\n"
    "    qh = q / np.linalg.norm(q, axis=1, keepdims=True)\n"
    "    raw = (qh * m[:, None]) @ k.T * SQRT_F\n"
    "    s_sym = 0.5 * (raw + raw.T)\n"
    "    a_anti = 0.5 * (raw - raw.T)\n"
    "    pi = (1.0 / (1.0 + np.exp(-(s_sym - L0_OFFSET)))) \\\n"
    "         * (1.0 / (1.0 + np.exp(-(a_anti / DIR_BETA))))\n"
    "    np.fill_diagonal(pi, 0.0)\n"
    "    return pi\n"
    "\n"
    "def shd_counts(a_bin, gt):\n"
    "    pred, truth = a_bin.astype(bool), gt.astype(bool)\n"
    "    extra = int((pred & ~truth).sum())\n"
    "    missing = int((~pred & truth).sum())\n"
    "    return extra + missing, extra, missing\n"
    "\n"
    "_cached_pi = CKP.get(\"PI\")\n"
    "if _cached_pi is not None and _cached_pi.shape == (len(EPOCHS), N, N):\n"
    "    PI = _cached_pi\n"
    "    print(\"loaded cached edge posterior\")\n"
    "else:\n"
    "    PI = np.stack([edge_posterior(q, K, m) for q, m in zip(Q, M)])   # (E, N, N)\n"
    "    cache_save(Q=Q, K=K, M=M, PI=PI)\n"
    "ABIN = PI >= DAG_THRESHOLD\n"
    "SHD_ALL = np.array([shd_counts(a, GT) for a in ABIN])            # (E, total, FP, FN)\n"
    "print(f\"SHD: init={SHD_ALL[0, 0]}  final={SHD_ALL[-1, 0]} \"\n"
    "      f\"({SHD_ALL[-1, 1]} extra, {SHD_ALL[-1, 2]} missing); \"\n"
    "      f\"GT edges={int(GT.sum())}\")"
)

c2 = (
    "# ---- Q-vs-M attribution ----------------------------------------------------------------\n"
    "# Recompute the posterior with one channel frozen at its post-init value.\n"
    "PI_qonly = np.stack([edge_posterior(Q[t], K, M[BASE])\n"
    "                     for t in range(len(EPOCHS))])     # only Q evolves\n"
    "PI_monly = np.stack([edge_posterior(Q[BASE], K, M[t])\n"
    "                     for t in range(len(EPOCHS))])     # only M evolves\n"
    "SHD_qonly = np.array([shd_counts(a, GT)[0] for a in PI_qonly >= DAG_THRESHOLD])\n"
    "SHD_monly = np.array([shd_counts(a, GT)[0] for a in PI_monly >= DAG_THRESHOLD])\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(7.6, 3.8))\n"
    "ax.plot(EPOCHS, SHD_ALL[:, 0], color=\"#000000\", lw=1.6, label=\"full (Q and M)\")\n"
    "ax.plot(EPOCHS, SHD_qonly, color=OKABE_ITO[0], lw=1.2, ls=\"--\",\n"
    "        label=\"only Q evolves (M frozen)\")\n"
    "ax.plot(EPOCHS, SHD_monly, color=OKABE_ITO[3], lw=1.2, ls=\":\",\n"
    "        label=\"only M evolves (Q frozen)\")\n"
    "ax.axhline(int(GT.sum()), color=\"#999999\", lw=0.8, ls=\"-.\",\n"
    "           label=f\"GT edges ({int(GT.sum())})\")\n"
    "ax.set_xlim(min(EPOCHS), max(EPOCHS))\n"
    "ax.set_xlabel(\"epoch [-]\")\n"
    "ax.set_ylabel(\"SHD [edges]\")\n"
    "ax.set_title(\"SHD attribution: query direction vs norm budget\")\n"
    "ax.legend(fontsize=9)\n"
    "fig.tight_layout()\n"
    "save_fig(fig, \"shd_qm_attribution\")\n"
    "plt.show()\n"
    "\n"
    "print(f\"final SHD: full={SHD_ALL[-1, 0]}  Q-only={SHD_qonly[-1]}  \"\n"
    "      f\"M-only={SHD_monly[-1]}  (post-init baseline: {SHD_ALL[BASE, 0]})\")"
)

cells = [nbf.v4.new_markdown_cell(md)] + [nbf.v4.new_code_cell(c) for c in (c1, c2)]
nbf.write(nbf.v4.new_notebook(cells=cells), "scripts/_nb_part8.ipynb")
print("part8 ok")
