"""Part 5: gradient field — offline reconstruction cell."""
import nbformat as nbf

md = (
    "## 4. The gradient field over training (offline reconstruction from checkpoints)\n"
    "\n"
    "Per-node **eval-mode HSIC gradients** reconstructed offline: each checkpoint is\n"
    "loaded, a forward pass is run on a FIXED eval sample (same rows for every\n"
    "checkpoint, seeded subsample of the dataset), and the HSIC term is\n"
    "differentiated w.r.t. the query embedding weights. Eval mode (dropout off)\n"
    "gives the denoised gradient: the direction the evidence points, free of\n"
    "batch/gate noise.\n"
    "\n"
    "Three views per node per checkpoint: **parent alignment** `cos(-g_i, c_i)`\n"
    "(positive = toward the true parents), **radial share** `|cos(g_i, q_i)|`\n"
    "(1 = no directional information), and **norm** `||g_i||`."
)

c1 = (
    "# ---- Offline gradient reconstruction (cached) --------------------------------------\n"
    "GRAD_STRIDE = 2       # every 2nd checkpoint (~20-epoch resolution); 1 = full\n"
    "GRAD_BATCH = 1024     # fixed eval sample size (seeded subsample of the dataset)\n"
    "GRAD_SEED = 0\n"
    "\n"
    "GRAD_CACHE = EXP_DIR / \"eval_cache\" / \"grad_field.npz\"\n"
    "\n"
    "\n"
    "def _grad_cache_key():\n"
    "    parts = [f\"{e}:{ckpts[e].name}:{ckpts[e].stat().st_mtime_ns}\" for e in EPOCHS]\n"
    "    bw = cfg.training.get(\"hsic_bandwidth_multipliers\", None)\n"
    "    consts = f\"stride={GRAD_STRIDE}|B={GRAD_BATCH}|seed={GRAD_SEED}|bw={bw!r}\"\n"
    "    return hashlib.sha256((consts + \"|\" + \"|\".join(parts)).encode()).hexdigest()\n"
    "\n"
    "\n"
    "def load_eval_batch():\n"
    "    d = np.load(DATA_DIR / \"ds.npz\")\n"
    "    rng = np.random.default_rng(GRAD_SEED)\n"
    "    idx = np.sort(rng.permutation(len(d[\"x\"]))[:GRAD_BATCH])\n"
    "    S = torch.tensor(np.asarray(d[\"s\"][idx]), dtype=torch.float32)\n"
    "    X = torch.tensor(np.asarray(d[\"x\"][idx]), dtype=torch.float32)\n"
    "    return S, X\n"
    "\n"
    "\n"
    "def query_grads_at(ckpt_path, S, X):\n"
    "    # Eval-mode per-node HSIC gradient rows at one checkpoint: (N, d).\n"
    "    from causaliT.training.forecasters.attention_selector_forecaster import (\n"
    "        AttentionSelectorForecaster)\n"
    "    from causaliT.utils.hsic_utils import hsic_cross_per_pair\n"
    "    fm = AttentionSelectorForecaster.load_from_checkpoint(ckpt_path,\n"
    "                                                          map_location=\"cpu\")\n"
    "    fm.eval()\n"
    "    with torch.enable_grad():\n"
    "        pred_x, _, _ = fm.forward(data_source=S, data_intermediate=X)\n"
    "        x_val = X[:, :, fm.val_idx]\n"
    "        if fm.homogeneous_nodes:\n"
    "            x_val = torch.cat([S[:, :, fm.val_idx], x_val], dim=1)\n"
    "        x_target = torch.nan_to_num(x_val)\n"
    "        residuals = x_target.squeeze() - pred_x.squeeze()\n"
    "        combined = (x_target.squeeze() if fm.homogeneous_nodes else\n"
    "                    torch.cat([S[:, :, fm.val_idx], x_target.squeeze()], dim=1))\n"
    "        hsic = hsic_cross_per_pair(\n"
    "            combined, residuals, sigma=fm.hsic_sigma,\n"
    "            adaptive_bandwidth=fm.hsic_adaptive_bandwidth, mode=fm.hsic_mode,\n"
    "            nhsic_epsilon=fm.nhsic_epsilon,\n"
    "            source_kernel=fm.hsic_kernel_source,\n"
    "            bandwidth_multipliers=getattr(fm, \"hsic_bandwidth_multipliers\", None),\n"
    "            pair_mask=None)\n"
    "        tabs = [fm.model.query_embed_S, fm.model.query_embed_X]\n"
    "        g = torch.autograd.grad(hsic,\n"
    "                                [t.embedding.weight for t in tabs],\n"
    "                                allow_unused=True)\n"
    "    rows = []\n"
    "    for g_, t in zip(g, tabs):\n"
    "        dmod = t.embedding.weight.shape[1]\n"
    "        rows.append(g_[1:].detach().double().numpy() if g_ is not None\n"
    "                    else np.zeros((t.embedding.weight.shape[0] - 1, dmod)))\n"
    "    return np.concatenate(rows, axis=0)\n"
    "\n"
    "\n"
    "G = None\n"
    "if GRAD_CACHE.exists():\n"
    "    try:\n"
    "        c = np.load(GRAD_CACHE, allow_pickle=False)\n"
    "        if str(c[\"cache_key\"]) == _grad_cache_key():\n"
    "            G, G_EPOCHS = c[\"G\"], c[\"G_EPOCHS\"]\n"
    "            print(\"loaded cached gradient field\")\n"
    "    except Exception:\n"
    "        pass\n"
    "if G is None:\n"
    "    S_ev, X_ev = load_eval_batch()\n"
    "    gidx = list(range(0, len(EPOCHS), GRAD_STRIDE))\n"
    "    if gidx[-1] != len(EPOCHS) - 1:\n"
    "        gidx.append(len(EPOCHS) - 1)\n"
    "    G = np.stack([query_grads_at(ckpts[EPOCHS[t]], S_ev, X_ev)\n"
    "                  for t in gidx])                       # (Eg, N, d)\n"
    "    G_EPOCHS = np.array([EPOCHS[t] for t in gidx])\n"
    "    GRAD_CACHE.parent.mkdir(parents=True, exist_ok=True)\n"
    "    np.savez(GRAD_CACHE, cache_key=np.str_(_grad_cache_key()), G=G,\n"
    "             G_EPOCHS=G_EPOCHS)\n"
    "    print(f\"gradient cache written: {GRAD_CACHE}\")\n"
    "\n"
    "GIDX = [int(np.where(np.array(EPOCHS) == e)[0][0]) for e in G_EPOCHS]"
)

cells = [nbf.v4.new_markdown_cell(md), nbf.v4.new_code_cell(c1)]
nbf.write(nbf.v4.new_notebook(cells=cells), "scripts/_nb_part5.ipynb")
print("part5 ok")
